### ISSUE TITLE
Polilines example in the UI

### ISSUE THREAD

**Issue by Oteo95** [asehmi/streamlit-label-studio-frontend#8]
Is there any plan to add to the examples the polilines option?

Best regards,
Alberto

**Comment by asehmi** [comment]
No plans, sorry. I built this more as a concrete example of implementing a Streamlit component, than an example of using Label Studio.

**Comment by zhentai-SMU** [comment]
Could you please offer any advice on this matter? I am looking to integrate a component for mask or polygon annotations. Your insights would be greatly appreciated.

**Comment by asehmi** [comment]
@Oteo95 @zhentai-SMU 

Hi - I have updated the app with image polygon and image segmentation examples. Please see the readme as LSF standalone has been deprecated! The Streamlit integration still works, but I'm not sure how long it will remain that way since the LSF package repository hasn't been updated.

Moving forward, you'd have to create a build of the editor (i.e. LSF) from the main LS repo, and point to these build JS and CSS files instead of taking them from the package repo.
